### ISSUE TITLE
Movie subtitles doesn't recognize Disney plus videos 

### ISSUE THREAD

**Issue by Ellachkaa** [gignupg/Movie-Subtitles#10]
I'm not able to display subtitles through the extension on https://www.apps.disneyplus.com/sa
Any idea why?

**Comment by gignupg** [comment]
Have you tried to disable all other extensions? It's possible that another extension is interfering with the video detection of Movie Subtitles. You could use [this](https://chrome.google.com/webstore/detail/disable-extensions-tempor/lcfdefmogcogicollfebhgjiiakbjdje?hl=en) chrome extension to temporarily disable all other extensions.
It's also possible that Disney Plus changed something in their code that interferes with the video detection. Would be interesting to know if other people are having the same issue. I'd test it myself but I don't have a Disney Plus subscription at the moment...
