### ISSUE TITLE
Error when clone the reposity and install dependencies

### ISSUE THREAD

**Issue by LostArrows27** [gignupg/Movie-Subtitles#11]
When i clone the repo and "npm install", it gives me this error, i have turn node-sass to lower version but still not work. Do you know any way to solve this ?
![image](https://user-images.githubusercontent.com/97510841/234502430-e7d2d44d-53eb-4760-9e14-c53a023303d1.png)

**Comment by gignupg** [comment]
Did you try running `npm install --force`?

**Comment by LostArrows27** [comment]
@gignupg i tried but it still give me this error, have you sucessfully install by using "npm install --force"
![image](https://user-images.githubusercontent.com/97510841/235335120-6c8d84cb-28e0-4e30-b84e-5f2526cc9fee.png)

**Comment by gignupg** [comment]
It's true, I get the same error! Were you able to fix it?

**Comment by LostArrows27** [comment]
@gignupg  i haven't be able to fix it but i think the main reason here is the version of node-sass and sass-loader

**Comment by gignupg** [comment]
@LostArrows27 ok, good to know! I'll fix it with the next update, although at moment there's no update planned.
