### ISSUE TITLE
suggestion for font color and height of subtitles

### ISSUE THREAD

**Issue by ghost** [gignupg/Movie-Subtitles#13]
There is only green color for font and I cannot choose any other font color. Could you please make it possible to choose other font colors, specifically white and black? And also could you make it possible to move the height of subtitles?

**Comment by gignupg** [comment]
At the moment I don't have time to add this feature to the official extension, but you can add it yourself relatively easily as I've explained [here](https://github.com/gignupg/Movie-Subtitles/issues/8). Hope this helps, let me know if you need help making it work!

**Comment by ghost** [comment]
Could u please write the code to change color of font color? I've added ' subtitleText.style.color = 'white'; ' but it didnt work... And also the code to customize the position of text.

**Comment by gignupg** [comment]
Hey @wonwater, you can drag and drop the subtitles and place them anywhere you want. Just make sure "edit mode" is disabled in the settings menu. You can open the settings menu by clicking on the Movie Subtitle icon. 
Regarding changing the color of the subtitles, I updated the code snippet and tested it on my computer. This should be working for you now:
```
javascript: (function () {
    const subtitleBackground = document.getElementsByClassName('jss4')[0];
    const subtitleText = document.getElementsByClassName('jss6')[0];
    const subtitleArrows = document.getElementsByClassName('jss26');
    subtitleBackground.style.backgroundColor = 'orange';
    subtitleText.style.color= 'purple';
    subtitleArrows[0].style.color = 'purple';
    subtitleArrows[1].style.color = 'purple';
})();
```

**Comment by ghost** [comment]
After adding the right up code, there appears only orange background without text color changing... T.T

**Comment by wonwater** [comment]
![제목 없음](https://github.com/gignupg/Movie-Subtitles/assets/141399486/ec9706ac-dae5-4101-ab50-8037e2fbe841)

**Comment by wonwater** [comment]
![제목 없음](https://github.com/gignupg/Movie-Subtitles/assets/141399486/b46e9ccc-62e6-4960-9566-fcb6ed8fd7cf)

**Comment by ghost** [comment]
![제목 없음](https://github.com/gignupg/Movie-Subtitles/assets/141399486/38774827-8a91-4878-8484-841e72e923d5)

**Comment by gignupg** [comment]
Interesting! Try adding `!important` to the line with the subtitle text color, like so:
`subtitleText.style.color= 'purple !important';`

**Comment by gignupg** [comment]
Interesting! I see you're using Language Reactor. Other extensions such as Language Reactor might interfere. Either try disabling Language Reactor and see if that works or try updating the line with the subtitle text color to the following:

```subtitleText.style.setProperty('color', 'purple', 'important');```
