### ISSUE TITLE
npm install ERROR

### ISSUE THREAD

**Issue by jerygood870208** [gignupg/Movie-Subtitles#16]
when I try to npm install this repository I got these error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: sass-loader@11.1.1
npm ERR! Found: node-sass@7.0.3
npm ERR! node_modules/node-sass
npm ERR!   dev node-sass@"^7.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional node-sass@"^4.0.0 || ^5.0.0 || ^6.0.0" from sass-loader@11.1.1
npm ERR! node_modules/sass-loader
npm ERR!   dev sass-loader@"^11.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: node-sass@6.0.1
npm ERR! node_modules/node-sass
npm ERR!   peerOptional node-sass@"^4.0.0 || ^5.0.0 || ^6.0.0" from sass-loader@11.1.1
npm ERR!   node_modules/sass-loader
npm ERR!     dev sass-loader@"^11.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Even using npm install --force will cause more errors. Is there any solution?

**Comment by gignupg** [comment]
Mmmm, try removing sass for second and then see if the installing goes through

**Comment by jerygood870208** [comment]
Replacing 'node-sass' with 'sass' in the package allows it to build successfully. Not sure about any potential impact. Thank you very much for your response.
