### ISSUE TITLE
Issue with displaying multiple subtitles at the same time

### ISSUE THREAD

**Issue by Phoenomenal** [gignupg/Movie-Subtitles#2]
Hello,  

I noticed problem/bug  in extension:  unfortunately does not properly display subtitles that normally present text at the top side of the screen and text at the bottom side of the screen at the same time. This is more common in anime (for example, there is a conversation in the background or an inscription pops up and at the same time another conversation or thoughts of the character on the plan or notes appear. There is an example in the attachment) but in Movie-Subtitles this does not happen and the text lines kinda interrupts each other (i mean 2-nd line will appear for a second and then other line replace it but they need to be at the same time) I think it will be possible to fix it, because in another chrome extension (+ sub) text appears one above the other in such places (i mean not exactly in upper and lower half of the screen like in example but one line appear above another). Example how it looks on +sub extension also in attachment
https://drive.google.com/file/d/1fMpDq6bB7LwKOkGegLAV2zMmBSsQ_lp0/view?usp=sharing - if interesting this is srt sub file for this video. Very easy to test because there are a few lines like this during first 30-40 seconds of video so you could easly test it on any video and you see what i mean when those lines begin interrupt each other instead of showing at the same time.
Could you please look at that and fix if possible.  Thanks in advance! 

![example](https://user-images.githubusercontent.com/68902338/137312688-80128d04-33de-4a1f-af2d-68858a1e486a.png)
![Screenshot_2](https://user-images.githubusercontent.com/68902338/137312699-21a0d245-4c3f-4765-9d37-33ad8709751e.png)

**Comment by gignupg** [comment]
That's a really good find! I wasn't aware of this. Also, thx for creating a separate issue for this!

I've created a small sample text file containing the first 50 seconds of `My Teenage RomCom SNAFU TOO`. Could you take a look at it to make sure everything is correct? I've highlighted the main text in green and the background text in orange. Let me know if it's correct!

Do you have more subtitle files with overlapping text? Do they all use curly braces to indicate background text? Feel free to send me some more subtitles especially if they use different formatting to indicate background text!

**Comment by gignupg** [comment]
Here the sample: https://docs.google.com/document/d/1r40WnIsYvW9AQX2XEJDJ0LwrEGdRF_SrX05phim3Gi0/edit?usp=sharing

**Comment by Phoenomenal** [comment]
> Here the sample: https://docs.google.com/document/d/1r40WnIsYvW9AQX2XEJDJ0LwrEGdRF_SrX05phim3Gi0/edit?usp=sharing

Yes,   thats right.

i think it would be a good idea to test with +Sub extension in the same time.  I id it with both My Teenage RomCom  and Saiki Kusou (link below)  and it makes good comparison and make it easier  to notice  the lines which wont appear correctly  -    https://chrome.google.com/webstore/detail/%20sub/lpobdmdfgjokempajoobgfdnhjbjlnpm
That extension display multiple lines  above each other, would be great if movie subtitles could do the same.   

https://drive.google.com/file/d/1nGeqINlV5yrq0DxzJDPmsi7gKai9lpIx/view?usp=sharing  -   this subs from 1 min 40  to 6 min have many  lines appearing on the same time. And from 5 min to 6 min  also.  I remember this whole series  (The Disastrous Life of Saiki K.)  being very dialogue heavy with lines appearing simultaneously + onscreen notifications (kitchen, hospital etc).   So this one is good for testing.   Sime lines  i noticed dont even appear at all on. when there are 2-3  different lines should appear at the same time.

also the same file but ass format before i converted to srt.   In text editor in shows near lines :  Main 2, Main 2 ita,  onscreen  i see main 2 and main 2 ita often overlaping each other.   Link to ass  file : https://drive.google.com/file/d/1vCjZD2AkyCbXlGT9CWqI3umynfpZy6Bz/view?usp=sharing


![Screenshot_3](https://user-images.githubusercontent.com/68902338/137401502-ce051623-153c-4903-9d49-ba00c834771c.png)

![Screenshot_5](https://user-images.githubusercontent.com/68902338/137401725-cf7d4fbf-cc8e-4c03-9536-bb863a18ebab.png)

![Screenshot_6](https://user-images.githubusercontent.com/68902338/137401854-36a7b526-92ef-4d2d-8766-f027749b0e0f.png)

**Comment by gignupg** [comment]
Cool thx! I'll use those two files for testing! I might be able to release a new version on the weekend, fingers crossed xD

**Comment by Phoenomenal** [comment]
Great news.    I also checked links right now and it seems i accidently put  wrong link where is suposed to be srt file i was testing .   This one i was testing  its an srt  for The Disastrous Life of Saiki K. 1 ep. :  https://drive.google.com/file/d/1nGeqINlV5yrq0DxzJDPmsi7gKai9lpIx/view?usp=sharing

**Comment by gignupg** [comment]
Great! Btw, is `.ass` a common subtitle format, or is it something old that nobody uses anymore nowadays?

**Comment by Phoenomenal** [comment]
I believe that .ass is a pretty common format, very often I download subtitles in this format.  Fansub groups upload in .ass or in .srt most of the time
I say 3 most popular right now is SubRip (.srt) ,  Advanced Sub Station Alpha (.ass)  and WebVTT (.vtt)

**Comment by gignupg** [comment]
Interesting! When downloading subtitles for feature films on opensubtitles.org they're mostly `.srt`

**Comment by Phoenomenal** [comment]
opensubtitles.org have most if not all releases in .srt    
 I say for movies and tv series .srt is a king.  For animation   .ass is pretty popular because  it allows for advanced typesetting.   
Good short example (look also for different colors on second lines appearing on the top of the screen  42- 50 seconds) https://www.youtube.com/watch?v=n_c-eKTisI0
SubRip probably cant do that.

**Comment by gignupg** [comment]
Yeah, that makes a lot of sense! 
I agree, `.srt` is not designed for displaying two subtitles at the same time. Also, Movie Subtitles is not designed for this. I've had a brief look at my code this morning and I realized that the whole system is relying on the fact that there is only one subtitle at a time. Skipping between dialogues, skipping silence, calculating the silence, etc. all rely on reading one subtitle at a time. I don't know if you've noticed but in Movie Subtitles dialogues never get removed. Instead, they get replaced by the next dialogue. If the next dialogue is more than 5 seconds away the silence indicator is shown. I would have to rebuild the whole underlying system to accommodate for displaying multiple subtitles simultaneously. So, unfortunately, way too much work for me at the moment ;(

**Comment by Phoenomenal** [comment]
Understand. Thanks for the info.   Will be using your extension for movies and tv series while for anime will be using other extensions (+sub or easysubs particularly) which which can display two or more subtitles at the same time.

Thank you again and good day!
