### ISSUE TITLE
Description indicates ability to copy text "in edit-mode" however no documentation or shortcut explains entering edit-mode

### ISSUE THREAD

**Issue by imperialboy3** [gignupg/Movie-Subtitles#5]

**Comment by gignupg** [comment]
Thx for pointing out this issue @imperialboy3. I've updated the section in the [README](https://github.com/gignupg/Movie-Subtitles#other-useful-features) that mentions this feature. Let me know if it is clearer now or how you would make it clearer!

**Comment by imperialboy3** [comment]
Now I see it, thanks. The problem was that it didn't ever occur to me to scroll down. I ended up cloning it and adding a keypress to auto-copy lol.
