### ISSUE TITLE
Sync on the fly

### ISSUE THREAD

**Issue by ginofalaci** [gignupg/Movie-Subtitles#6]
Would it be possible to add a shortcut to sync the subtitle like: +sync 1 second later, - sync one second earlier, so that it will be easier than stop the movie, try another time for sync etc... when you do it three time to try to get the good sync, its not nice. so that would be very useful.

**Comment by gignupg** [comment]
@ginofalaci that's a great idea! And it's relatively easy to implement. I'll work on it and post an update here when it's done!

**Comment by gignupg** [comment]
All right, the new version with the sync shortcuts is now published. @ginofalaci make sure to update Movie Subtitles to version 1.7.0 if it hasn't already updated automatically!

**Comment by ginofalaci** [comment]
Cool, thank you I will try it soon.

Envoyé de mon iPhone

**Comment by ginofalaci** [comment]
It’s working fine, thank you very much it’s great!

Envoyé de mon iPhone

**Comment by ginofalaci** [comment]
Hi me again, ...
Could you please, make it possible to dismiss the 'syncronisation succesfull", when you follow an programm and need to sync on the fly, you dont want to miss any sentence and see all the time this message, you want to be able to see the subtitles .... eventually any flag or star in a corner to say its syncing, but please not where the subtitles appear it makes it almost useless...
You need to understand what im using it for:  Some talk shows that are subtitled on the fly, so subtitles appear with like 10-15 seconds late,  and also are not regular with the talks. because sometime, the guy is writing late... (tough job...). So im downloading the subtitles to be able to show this with subtitles synced (for my old mom that cant understand all text talks, but can follow well reading the subtitles...) SO I need to adjust live, few seconds more, or less, and it changes during the show...hope you understand the need.. Thanks in advance. Ive edit the file to remove the 'syncronisation successful' but it still appear, maybe need to restart Chrome, but I cant at the moment...

**Comment by gignupg** [comment]
Hi @ginofalaci, 
Thanks for letting me know about this issue and sorry for the late response!
I can definitely see how that's annoying! 
I will try to fix it this weekend and post an update here once the new version is out!

**Comment by gignupg** [comment]
@ginofalaci, the new version is published! Make sure to update to version 1.7.1!

**Comment by ginofalaci** [comment]
Hey hello there, 
Thank you it’s perfect! Much more useful now. Great work thanks
Jean

Envoyé de mon iPhone
