### ISSUE TITLE
How to remove "<<"">>" from subtitles?

### ISSUE THREAD

**Issue by haildceu1** [gignupg/Movie-Subtitles#7]
I love this project because it's the only extension that works for hbo max. But is there any way to remove these punctuations? Thx!

**Comment by gignupg** [comment]
Hey @haildceu1, that's a good point! The punctuation symbols "<<"">>" are actually buttons that allow you to jump between sentences. It's a feature for people who are using the extension to learn a foreign language so they can repeat a phrase if they don't understand it the first time around. 
Though, I guess most people never use these buttons anyway. I'll think of something and let you know once it's done!

**Comment by gignupg** [comment]
@haildceu1, I decided to hide the "<<"">>" buttons by default! Now they will only be visible if you toggle the silence indicator on! Make sure to update to version 1.8.1 to see the changes!
