### ISSUE TITLE
font/text suggestion

### ISSUE THREAD

**Issue by x247Shufflingx** [gignupg/Movie-Subtitles#8]
Could you create an option to add our own font and customize it more?

I'd really love to add a black outline/shadow to the white text!

Thanks!

**Comment by gignupg** [comment]
Hey @x247Shufflingx, thx for your suggestion! 
I'm not sure if this is something that would be useful to a lot of people. Also, I'd prefer to keep the UI as simple as possible. 
However, I've created a bookmarklet for you to change the font and add a shadow for yourself. Simply copy the following code and follow the instructions of [this README.md](https://github.com/gignupg/Bookmarklets) file:
```
javascript: (function () {
    const subtitleText = document.getElementsByClassName('jss6')[0];
    subtitleText.style.fontFamily = 'monospace';
    subtitleText.style.textShadow = '2px 2px 5px red';
})();
```
This applies the `monospace` font with a `red` shadow. Feel free to adjust the shadow or font to your needs!
