### ISSUE TITLE
Amazon Prime "No Video Detected"

### ISSUE THREAD

**Issue by TimurKelman** [gignupg/Movie-Subtitles#9]
The extension didn't detect a video that is on the page.

![image](https://user-images.githubusercontent.com/348150/209328561-94c496a1-6a94-4911-9d87-d4d99965329e.png)

**Comment by gignupg** [comment]
Hey @TymurGubayev, thanks for reporting this issue! 
Could you add some more detail? For me, it works flawlessly on amazon.de! Is it possible that you clicked the Movie Subtitle icon too soon? Before the page was fully loaded?
